//------------------------------------------------------------ maps
const MAPS={
mosshollow:{out:1,mus:'over',edges:{N:{m:'route1',d:-1}},
g:['TTTTTTTT-TTTTTTTTT',
   'T..f....-....f...T',
   'T.RRR...-...RRR..T',
   'T.RRR...-...RRR..T',
   'T.WoW...-...WoW..T',
   'T.WDW...-...WDW..T',
   'T.......-........T',
   'T..S....-...f....T',
   'T..------------..T',
   'T.........BBBBBB.T',
   'T.f.......BBBBBB.T',
   'T.........WWDWWW.T',
   'T.f..............T',
   'TTTTTTTTTTTTTTTTTT'],
warps:[{x:3,y:5,m:'home',tx:4,ty:6,dir:'u'},{x:13,y:5,m:'house1',tx:4,ty:6,dir:'u'},{x:12,y:11,m:'lab',tx:5,ty:7,dir:'u'}],
npcs:[{x:8,y:1,pal:'aide',dir:'d',dscript:'aide'},
 {x:9,y:12,pal:'rook',dir:'r',req:'gotstarter',not:'rival1',tr:{name:'RIVAL ROOK',rival:1,m:300,sight:4,f:'rival1',b:["ROOK: There you are! Show me that starter isn't wasted on you!"],a:["ROOK: Tch. Lucky ember. I'm off to flatten the THORNBURY gym."],win:'rival1win'}},
 {x:5,y:10,pal:'kid',dir:'d',mv:1,d:['Wild KIN hide in tall grass. Walk in, get jumped. Fun!']}],
trig:[{x:8,y:2,s:'aide',not:'snares'}],
signs:{'3,7':'MOSSHOLLOW VILLAGE - Where journeys take root.'},
items:[],exam:[],enc:null},

home:{out:0,mus:'over',
g:['##########','#hh____ee#','#________#','#__aa____#','#________#','#________#','#___m____#','####d#####'],
warps:[{x:4,y:7,m:'mosshollow',tx:3,ty:6,dir:'d'}],
npcs:[{x:6,y:4,pal:'mom',dir:'d',mv:1,dscript:'mom'}],
exam:[{x:7,y:1,s:'bed'},{x:8,y:1,s:'bed'}],trig:[],signs:{},items:[],enc:null},

house1:{out:0,mus:'over',
g:['##########','#hh____hh#','#________#','#__aa____#','#________#','#________#','#________#','####d#####'],
warps:[{x:4,y:7,m:'mosshollow',tx:13,ty:6,dir:'d'}],
npcs:[{x:6,y:3,pal:'oldman',dir:'d',mv:1,d:["Three badges shine in Solvane: BRIAR's BLOOM, BRAVA's CINDER, BRONTE's SURGE.",'Earn all three, then knock on the AURELIA gate up at STORMREACH.']}],
exam:[],trig:[],signs:{},items:[],enc:null},

lab:{out:0,mus:'over',
g:['############','#hhhhhhhhhh#','#__________#','#_____aaa__#','#__________#','#__________#','#__________#','#__________#','#####d######'],
warps:[{x:5,y:8,m:'mosshollow',tx:12,ty:12,dir:'d'}],
npcs:[{x:3,y:4,pal:'prof',dir:'r',dscript:'prof'}],
exam:[{x:6,y:3,s:'orb0'},{x:7,y:3,s:'orb1'},{x:8,y:3,s:'orb2'}],
trig:[],signs:{},items:[],enc:null},

route1:{out:1,mus:'over',edges:{S:{m:'mosshollow',d:1},N:{m:'thornbury',d:4}},
g:['TTTTTT-TTTTTTT',
   'T.gg..-...gg.T',
   'T.gg..-...gg.T',
   'T.gg..-..f...T',
   'T.....-......T',
   'T..f..-......T',
   'Tgg...-..gg..T',
   'Tgg.S.-..gg..T',
   'Tgg...-..gg..T',
   'TLLLLL-..LLLLT',
   'T.....-......T',
   'T.gg..-..gg..T',
   'T.gg..-..gg..T',
   'T.f...-......T',
   'T.....--.....T',
   'T..gg..-.gg..T',
   'T..gg..-.gg..T',
   'T......-.f...T',
   'TLLLL..-.LLLLT',
   'T......-.....T',
   'T.gg...-..gg.T',
   'T.gg...-..gg.T',
   'T...f..-.....T',
   'T......-.....T',
   'T.S....-.....T',
   'TTTTTTT-TTTTTT'],
warps:[],
npcs:[{x:10,y:13,pal:'kid',dir:'l',tr:{name:'YOUNGSTER TODD',team:[[7,4]],m:120,sight:4,f:'tr_r1a',b:['My SCURRIT is the fastest thing on ROUTE 1!'],a:['It zoomed right past me...']}},
 {x:4,y:22,pal:'lass',dir:'r',tr:{name:'LASS MIA',team:[[9,3],[13,4]],m:100,sight:3,f:'tr_r1b',b:['My garden friends and I will not lose!'],a:['Oh! My poor petals!']}}],
trig:[],signs:{'4,7':'ROUTE 1 - North: THORNBURY TOWN.','2,24':'Tall grass hides wild KIN! Carry SNARES.'},
items:[{x:2,y:4,it:'snare',q:3,f:'it_r1a'},{x:10,y:17,it:'tonic',q:1,f:'it_r1b'}],
exam:[],
enc:{m:[[7,2,4,30],[9,2,4,30],[13,2,4,20],[23,3,3,10],[11,2,4,10]],
     d:[[7,2,4,35],[9,2,4,30],[11,2,4,25],[13,2,4,10]],
     n:[[19,2,4,40],[7,2,4,25],[11,2,4,20],[21,3,5,15]]}},

thornbury:{out:1,mus:'over',edges:{S:{m:'route1',d:-4},E:{m:'route2',d:-3}},
g:['TTTTTTTTTTTTTTTTTTTTTT',
   'T..f.................T',
   'T.RRRR...BBBB...PPPPPT',
   'T.RRRR...BBBB...PPPPPT',
   'T.WDWW...WWDW...WWDWWT',
   'T..............S.....T',
   'T..f......f..........T',
   'T....................T',
   'T---------------------',
   'T.........-..........T',
   'T..S......-...f......T',
   'T.f.......-..........T',
   'T.........-....f.....T',
   'T.........-..........T',
   'T.........-..........T',
   'TTTTTTTTTT-TTTTTTTTTTT'],
warps:[{x:3,y:4,m:'haven1',tx:5,ty:6,dir:'u'},{x:11,y:4,m:'shop1',tx:4,ty:6,dir:'u'},{x:18,y:4,m:'gym1',tx:6,ty:11,dir:'u'}],
npcs:[{x:13,y:6,pal:'kid',dir:'d',mv:1,d:['Two NEW Kin types were just discovered: ALLOY and UMBRAL!','Gramps says the old type chart is obsolete. Wild times!']},
 {x:5,y:12,pal:'oldman',dir:'d',mv:1,d:['Different KIN prowl by morning, day and night.','The clock matters, kid. Some only ever show after dark.']},
 {x:16,y:6,pal:'lass',dir:'d',mv:1,d:['Leader BRIAR grows FLORA Kin.','EMBER or GALE moves will prune her right down!']},
 {x:15,y:11,pal:'vendor',dir:'d',time:'n',dscript:'vendor'}],
trig:[],
signs:{'3,10':'THORNBURY TOWN - The hedge and hearth town.','15,5':'THORNBURY KIN GYM - Leader BRIAR: The Budding Wall.'},
labels:[{x:3,y:3,t:'HAVEN'},{x:11,y:3,t:'MART'},{x:18,y:3,t:'GYM'}],
items:[],exam:[],enc:null},

haven1:{out:0,mus:'over',
g:['############','#_________p#','#__________#','#__kkkkkk__#','#__________#','#__________#','#__________#','#####d######'],
warps:[{x:5,y:7,m:'thornbury',tx:3,ty:5,dir:'d'}],
npcs:[{x:5,y:2,pal:'nurse',dir:'d',dscript:'nurse'}],
exam:[{x:10,y:1,s:'pc'}],trig:[],signs:{},items:[],enc:null},

shop1:{out:0,mus:'over',
g:['##########','#h_______#','#________#','#kkkk____#','#________#','#________#','#________#','####d#####'],
warps:[{x:4,y:7,m:'thornbury',tx:11,ty:5,dir:'d'}],
npcs:[{x:2,y:2,pal:'clerk',dir:'d',dscript:'shop1'}],
exam:[],trig:[],signs:{},items:[],enc:null},

gym1:{out:0,mus:'gym',gates:1,
g:['##############',
   '#__n______n__#',
   '#HHHHHHZHHHHH#',
   '#__________U_#',
   '#HHHHYHHHHHHH#',
   '#____________#',
   '#HHHHH_HHHHHH#',
   '#____________#',
   '#HHHHHHHHHH_H#',
   '#____________#',
   '#uHHHHHHHHHHH#',
   '#____________#',
   '#_____d______#',
   '##############'],
warps:[{x:6,y:12,m:'thornbury',tx:18,ty:5,dir:'d'}],
npcs:[{x:7,y:1,pal:'briar',dir:'d',tr:{name:'LEADER BRIAR',team:[[13,10],[14,12]],m:1200,sight:0,f:'tr_briar',win:'badge1',b:['BRIAR: Welcome to the Budding Wall.','My garden does not wilt. Show me your roots!'],a:['Pruned! Fair and square.']}},
 {x:9,y:9,pal:'lass',dir:'l',tr:{name:'GARDENER IVY',team:[[11,8],[13,9]],m:240,sight:5,f:'tr_ivy',b:['Only green thumbs pass me!'],a:['Composted...']}}],
trig:[],signs:{},items:[],exam:[],enc:null},

route2:{out:1,mus:'over',edges:{W:{m:'thornbury',d:3}},
g:['TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
   'T.......................rrrrrT',
   'T..ggg......ggggg.......rrrrrT',
   'T..ggg......ggggg.......rrrrrT',
   'T..ggg..................rrCrrT',
   '---------------------------..T',
   'T...gg.........gggg....S.....T',
   'T...gg.........gggg..........T',
   'T....f.......................T',
   'T............................T',
   'T............................T',
   'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT'],
warps:[{x:26,y:4,m:'cave',tx:2,ty:8,dir:'r'}],
npcs:[{x:2,y:6,pal:'oldman',dir:'d',time:'m',dscript:'keeper'},
 {x:10,y:4,pal:'kid',dir:'d',tr:{name:'BUG KID NILS',team:[[11,6],[11,6],[15,7]],m:170,sight:2,f:'tr_r2a',b:['Bugs! Bugs! BUGS!'],a:['They all curled up...']}},
 {x:17,y:7,pal:'lass',dir:'u',tr:{name:'PICNICKER ROSA',team:[[28,7],[13,7]],m:200,sight:3,f:'tr_r2b',b:['You stepped on my picnic blanket!'],a:['And now my juice is spilled too.']}},
 {x:22,y:4,pal:'hiker',dir:'d',tr:{name:'HIKER BORIS',team:[[17,8],[17,8]],m:280,sight:2,f:'tr_r2c',b:['These boulders are my babies!'],a:['Rocked and rolled...']}}],
trig:[],
signs:{'23,6':'EAST: HOLLOW CAVE - Mind the dark. - The Gloam? Never heard of them. -MGMT'},
items:[{x:6,y:8,it:'juneberry',q:1,f:'it_r2a'},{x:26,y:9,it:'quickquill',q:1,f:'it_r2b'}],
exam:[],
enc:{m:[[9,5,7,25],[13,5,7,25],[15,5,7,25],[23,5,7,5],[7,5,7,20]],
     d:[[15,5,8,30],[11,5,7,20],[13,5,7,25],[9,5,7,25]],
     n:[[19,5,8,35],[21,5,8,25],[27,5,8,25],[7,5,7,15]]}},

cave:{out:0,mus:'cave',
g:['xxxxxxxxxxxxxxxxxxxx',
   'xxxxxxxxqqqqqqqqqqqx',
   'xxxxxxxxqqqqqqqqqqqx',
   'xxxxxxxxqqqxxxxxxxxx',
   'xxxxxxxxqqqxxxxxxxxx',
   'xxxxxxqqqqqqqxxxxxxx',
   'xqqqqxqqqqqqqxxxxxxx',
   'xqqqqxqqqqqqqqqqqqdx',
   'xdqqqqqqqqqqqxxxxxxx',
   'xqqqqxqqqqqqqxxxxxxx',
   'xqqqqxqqqqqqqxxxxxxx',
   'xxxxxxxqqqqqqxxxxxxx',
   'xxxxxxxqqqqqqqqqqxxx',
   'xxxxxxxqqqqqqqqqqxxx',
   'xxxxxxxxxxxxxxxxxxxx',
   'xxxxxxxxxxxxxxxxxxxx'],
warps:[{x:1,y:8,m:'route2',tx:26,ty:5,dir:'d'},{x:18,y:7,m:'route3',tx:2,ty:7,dir:'r'}],
npcs:[{x:3,y:6,pal:'hiker',dir:'d',tr:{name:'HIKER CLINT',team:[[17,9],[17,10]],m:320,sight:3,f:'tr_cva',b:['I apologize to every pebble I step on. You should too!'],a:['Sorry, pebbles. I let you down.']}},
 {x:9,y:4,pal:'grunt',dir:'d',not:'gloamgone',tr:{name:'GLOAM GRUNT',team:[[19,9],[27,9]],m:300,sight:2,f:'tr_cvb',b:['The GLOAM SYNDICATE will snuff out Solvane, light by light!'],a:['My shift is SO over.']}},
 {x:14,y:7,pal:'grunt',dir:'l',not:'gloamgone',tr:{name:'GLOAM GRUNT',team:[[19,10]],m:300,sight:4,f:'tr_cvc',b:['No witnesses past this point!'],a:['Witness... protection?']}},
 {x:15,y:1,pal:'officer',dir:'l',not:'gloamgone',tr:{name:'OFFICER VESPER',team:[[27,11],[19,12]],m:600,sight:4,f:'tr_vesper',win:'gloamwin',b:['VESPER: These ALLOY CORES will fuel our eclipse engine.','You have seen far too much, little Keeper.'],a:['Impossible...!']}},
 {x:17,y:2,pal:'miner',dir:'d',dscript:'miner'}],
trig:[],signs:{},
items:[{x:16,y:12,it:'primesnare',q:1,f:'it_cva'},{x:12,y:13,it:'irontalisman',q:1,f:'it_cvb'},{x:3,y:10,it:'bitterroot',q:1,f:'it_cvc'}],
exam:[],
enc:{m:[[17,7,10,40],[27,7,10,30],[29,8,10,12],[22,8,10,18]],
     d:[[17,7,10,40],[27,7,10,30],[29,8,10,12],[22,8,10,18]],
     n:[[22,8,11,35],[27,7,10,30],[17,7,10,23],[29,8,10,12]]}},

route3:{out:1,mus:'over',edges:{E:{m:'cindervale',d:2}},
g:['TTTTTTTTTTTTTTTTTTTTTTTTTT',
   'T...f....gg..T....gg.....T',
   'T...S....gg..T.f..gg.....T',
   'T........gg..T....gg.....T',
   'T............T...........T',
   'T..gg........T.....gg....T',
   'T............T..----------',
   'TC---------------.gg.....T',
   'T..www..gg...T...gg......T',
   'T..www..gg...T...gg......T',
   'T....f.......T...........T',
   'TTTTTTTTTTTTTTTTTTTTTTTTTT'],
warps:[{x:1,y:7,m:'cave',tx:17,ty:7,dir:'l'}],
npcs:[{x:9,y:4,pal:'kid',dir:'d',tr:{name:'BIRD TAMER SKY',team:[[9,11],[21,12]],m:380,sight:3,f:'tr_r3a',b:['My birds own this sky!'],a:['Grounded. All of us.']}},
 {x:18,y:8,pal:'kid',dir:'u',tr:{name:'SCHOOL KID PIP',team:[[25,12],[15,11]],m:360,sight:2,f:'tr_r3b',b:['Pop quiz: can you beat me? Show your work!'],a:['I got an F in battling...']}}],
trig:[{x:13,y:7,s:'rival2',not:'rival2'}],
signs:{'4,2':'ROUTE 3 - East: CINDERVALE TOWN.'},
items:[{x:4,y:1,it:'supertonic',q:1,f:'it_r3a'},{x:21,y:9,it:'powerband',q:1,f:'it_r3b'}],
exam:[],
enc:{m:[[25,10,13,30],[28,10,13,22],[9,10,12,18],[15,10,12,15],[13,10,12,15]],
     d:[[25,10,13,30],[28,10,13,22],[9,10,12,18],[15,10,12,15],[13,10,12,15]],
     n:[[19,10,13,28],[21,10,13,22],[27,10,13,20],[25,10,13,15],[28,10,13,15]]}},

cindervale:{out:1,mus:'over',edges:{W:{m:'route3',d:-2},N:{m:'route4',d:0}},
g:['TTTTTTTTT-TTTTTTTTTT',
   'T...FFFF.-.FFFF....T',
   'T.........S........T',
   'T.RRRR...BBBB.PPPPPT',
   'T.RRRR...BBBB.PPPPPT',
   'T.WDWW...WWDW.WWDWWT',
   'T..................T',
   'T.....f.......S....T',
   '----------------...T',
   'T..................T',
   'T....f.......f.....T',
   'T..S...............T',
   'T..................T',
   'T..................T',
   'T..................T',
   'TTTTTTTTTTTTTTTTTTTT'],
warps:[{x:3,y:5,m:'haven2',tx:5,ty:6,dir:'u'},{x:11,y:5,m:'shop2',tx:4,ty:6,dir:'u'},{x:16,y:5,m:'gym2',tx:6,ty:11,dir:'u'}],
npcs:[{x:4,y:6,pal:'guard',dir:'d',d:['STORMREACH lies north now, up past ROUTE 4.','Leader BRONTE guards the road to the AURELIA gate.']},
 {x:13,y:10,pal:'oldman',dir:'d',mv:1,d:['Legend says NOCTELK walks the three roads, but only at night.','It never stays. Strike true, or snare it before it slips away.']},
 {x:6,y:12,pal:'kid',dir:'d',mv:1,d:['Once I saw a KIN that GLEAMED like treasure!','One in a thousand, gramps says. Maybe one in 64...']}],
trig:[],
signs:{'10,2':'NORTH: ROUTE 4 to STORMREACH and the third gym.','14,7':'CINDERVALE KIN GYM - Leader BRAVA: The Wildfire Waltz.','3,11':'CINDERVALE TOWN - Warm hearths, warmer hearts.'},
labels:[{x:3,y:4,t:'HAVEN'},{x:11,y:4,t:'MART'},{x:16,y:4,t:'GYM'}],
items:[],exam:[],enc:null},

haven2:{out:0,mus:'over',
g:['############','#_________p#','#__________#','#__kkkkkk__#','#__________#','#__________#','#__________#','#####d######'],
warps:[{x:5,y:7,m:'cindervale',tx:3,ty:6,dir:'d'}],
npcs:[{x:5,y:2,pal:'nurse',dir:'d',dscript:'nurse'}],
exam:[{x:10,y:1,s:'pc'}],trig:[],signs:{},items:[],enc:null},

shop2:{out:0,mus:'over',
g:['##########','#h_______#','#________#','#kkkk____#','#________#','#________#','#________#','####d#####'],
warps:[{x:4,y:7,m:'cindervale',tx:11,ty:6,dir:'d'}],
npcs:[{x:2,y:2,pal:'clerk',dir:'d',dscript:'shop2'}],
exam:[],trig:[],signs:{},items:[],enc:null},

gym2:{out:0,mus:'gym',
g:['##############',
   '#____________#',
   '#iriirriiiiri#',
   '#iiiiiiriiiii#',
   '#riiriiiiiiii#',
   '#iiiiiiiiriii#',
   '#iiiiiiiiiiir#',
   '#iiiiiriiiiii#',
   '#iiiiiiiiirii#',
   '#iiriiiiriiii#',
   '#iiiiiiiiiiii#',
   '#____________#',
   '#_____d______#',
   '##############'],
warps:[{x:6,y:12,m:'cindervale',tx:16,ty:6,dir:'d'}],
npcs:[{x:6,y:1,pal:'brava',dir:'d',tr:{name:'LEADER BRAVA',team:[[29,14],[2,16]],m:1600,sight:0,f:'tr_brava',win:'badge2',b:['BRAVA: Welcome to the Wildfire Waltz!','Mind the waxed floor. Now... shall we dance?'],a:['Burned out! What a lead partner you are.']}},
 {x:3,y:11,pal:'kid',dir:'r',tr:{name:'BURNER COLE',team:[[29,13]],m:420,sight:4,f:'tr_g2a',b:['Feel the heat!'],a:['I flamed out.']}},
 {x:10,y:11,pal:'lass',dir:'l',tr:{name:'BURNER TESSA',team:[[1,12],[29,13]],m:420,sight:4,f:'tr_g2b',b:['This floor? I waxed it myself!'],a:['Slipped up...']}}],
trig:[],signs:{},items:[],exam:[],enc:null},

route4:{out:1,mus:'over',edges:{S:{m:'cindervale',d:0},N:{m:'stormreach',d:0}},
g:['TTTTTT-TTTTTTT',
   'T.gg......gg.T',
   'T.gg......gg.T',
   'T...f....f...T',
   'T.gg......gg.T',
   'T.gg......gg.T',
   'T............T',
   'T...gg..gg...T',
   'T...gg..gg...T',
   'T............T',
   'T..f......f..T',
   'T.S..........T',
   'T............T',
   'TTTTTTTTT-TTTT'],
warps:[],
npcs:[{x:3,y:6,pal:'kid',dir:'d',tr:{name:'SPARKY LIV',team:[[15,16],[16,17]],m:340,sight:3,f:'tr_r4a',b:['Static cling? I call it a hug!'],a:['Grounded out...']}},
 {x:10,y:9,pal:'hiker',dir:'u',tr:{name:'RANGER NOLAN',team:[[10,18],[31,17]],m:400,sight:3,f:'tr_r4b',b:['The storms up here breed strong KIN.'],a:['Blown clean away.']}}],
trig:[],
signs:{'2,11':'ROUTE 4 - North: STORMREACH. Mind the live wires.'},
items:[{x:6,y:3,it:'apexsnare',q:1,f:'it_r4a'},{x:2,y:9,it:'supertonic',q:1,f:'it_r4b'}],
exam:[],
enc:{m:[[15,16,19,30],[9,16,19,25],[7,16,18,20],[16,18,20,15],[31,18,20,10]],
     d:[[15,16,19,30],[9,16,19,25],[16,18,20,20],[31,18,20,15],[27,17,19,10]],
     n:[[19,17,20,30],[27,17,20,25],[16,18,21,20],[31,19,22,15],[15,16,19,10]]}},

stormreach:{out:1,mus:'over',edges:{S:{m:'route4',d:0}},
g:['TTTTTTTTTTTTTTTTTT',
   'T...FFF.FF.FFF...T',
   'T......S.........T',
   'T................T',
   'T.RRRR..BBBB.PPPPT',
   'T.RRRR..BBBB.PPPPT',
   'T.WDWW..WWDW.WWDWT',
   'T................T',
   'T.....f....f.....T',
   'T................T',
   'T......S.........T',
   'T................T',
   'T................T',
   'TTTTTT-TTTTTTTTTTT'],
warps:[{x:3,y:6,m:'haven3',tx:5,ty:6,dir:'u'},{x:10,y:6,m:'shop3',tx:4,ty:6,dir:'u'},{x:15,y:6,m:'gym3',tx:6,ty:11,dir:'u'}],
npcs:[{x:7,y:3,pal:'guard',dir:'d',d:['The AURELIA gate is sealed tight.','Eight more HAVENS wait beyond. Next chapter, KEEPER!']},
 {x:5,y:9,pal:'lass',dir:'d',mv:1,d:['Leader BRONTE rides the current itself.','Bring STONE moves - VOLT fizzles on solid ground!']},
 {x:12,y:9,pal:'kid',dir:'d',mv:1,d:['A new KIN, ARCLEON, prowls ROUTE 4!','Storms trail it like a puppy.']}],
trig:[],
signs:{'7,2':'AURELIA GATE - SEALED. The AURELIA region waits beyond... next season!','7,10':'STORMREACH - The frontier under the live sky.'},
labels:[{x:3,y:5,t:'HAVEN'},{x:10,y:5,t:'MART'},{x:15,y:5,t:'GYM'}],
items:[],exam:[],enc:null},

haven3:{out:0,mus:'over',
g:['############','#_________p#','#__________#','#__kkkkkk__#','#__________#','#__________#','#__________#','#####d######'],
warps:[{x:5,y:7,m:'stormreach',tx:3,ty:7,dir:'d'}],
npcs:[{x:5,y:2,pal:'nurse',dir:'d',dscript:'nurse'}],
exam:[{x:10,y:1,s:'pc'}],trig:[],signs:{},items:[],enc:null},

shop3:{out:0,mus:'over',
g:['##########','#h_______#','#________#','#kkkk____#','#________#','#________#','#________#','####d#####'],
warps:[{x:4,y:7,m:'stormreach',tx:10,ty:7,dir:'d'}],
npcs:[{x:2,y:2,pal:'clerk',dir:'d',dscript:'shop3'}],
exam:[],trig:[],signs:{},items:[],enc:null},

gym3:{out:0,mus:'gym',
g:['##############',
   '#_n________n_#',
   '###>>>_#######',
   '###^##########',
   '###^##########',
   '###^##########',
   '###^##########',
   '###^##########',
   '###^##########',
   '#____________#',
   '#____________#',
   '#____________#',
   '#_____d______#',
   '##############'],
warps:[{x:6,y:12,m:'stormreach',tx:15,ty:7,dir:'d'}],
npcs:[{x:6,y:1,pal:'bronte',dir:'d',tr:{name:'LEADER BRONTE',team:[[15,18],[16,20],[31,23]],m:2000,sight:0,f:'tr_bronte',win:'badge3',b:['BRONTE: Welcome to the live current!','Stand still and the floor will move you. Ready?'],a:['Discharged! A shocking run, KEEPER.']}},
 {x:2,y:10,pal:'kid',dir:'r',tr:{name:'AMP COLT',team:[[15,17],[16,18]],m:460,sight:4,f:'tr_g3a',b:['Feel that buzz?'],a:['Short-circuited.']}},
 {x:10,y:10,pal:'lass',dir:'l',tr:{name:'COIL DANA',team:[[16,19]],m:460,sight:4,f:'tr_g3b',b:['You wont find the leader on foot!'],a:['Grounded.']}}],
trig:[],signs:{},items:[],exam:[],enc:null}
};
const DEXN=SP.length-1; // the Kindex grows automatically as species are appended

